services:
  web:
    build: .
    ports:
      - "9292:9292"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - PORT=9292
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  bundle_cache: